[tool.bumpversion]
current_version = "0.8.8"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = true
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
commit = true
message = "Bump version: {current_version} → {new_version}"
moveable_tags = []
commit_args = ""
setup_hooks = []
pre_commit_hooks = ["cd back && uv lock", "git add back/uv.lock"]
post_commit_hooks = []

[[tool.bumpversion.files]]
filename = "back/pyproject.toml"

[[tool.bumpversion.files]]
filename = "back/src/whombat/__init__.py"

[[tool.bumpversion.files]]
filename = "front/package.json"

[[tool.bumpversion.files]]
filename = "front/src/app/version.ts"
