version: "3"
services:
  app:
    build: .
    command: python app.py
    environment:
      - WHOMBAT_DEV=true
      - WHOMBAT_SAME_SITE=none
    ports:
      - 5000:5000
    volumes:
      - ./back:/code
