import {
  RectangleStackIcon,
  PencilSquareIcon,
  ClipboardDocumentCheckIcon,
  DocumentMagnifyingGlassIcon,
  HomeIcon,
  InboxIcon,
  ArrowRightOnRectangleIcon,
  Cog8ToothIcon,
  MagnifyingGlassIcon,
  DocumentDuplicateIcon,
  ArchiveBoxIcon,
  PlusIcon,
  CalendarIcon,
  ChevronRightIcon,
  ChevronLeftIcon,
  ArrowUturnLeftIcon,
  ArrowSmallRightIcon,
  ArrowSmallLeftIcon,
  ChevronUpDownIcon,
  CheckIcon,
} from "@heroicons/react/24/outline";

function WhombatIcon() {
  return <img src="/whombat.svg" />;
}

export {
  WhombatIcon,
  RectangleStackIcon as DatasetsIcon,
  PencilSquareIcon as AnnotationProjectIcon,
  DocumentMagnifyingGlassIcon as ExplorationIcon,
  ClipboardDocumentCheckIcon as EvaluationIcon,
  HomeIcon,
  ArchiveBoxIcon as DatasetIcon,
  DocumentDuplicateIcon as RecordingsIcon,
  InboxIcon as MessagesIcon,
  Cog8ToothIcon as SettingsIcon,
  ArrowRightOnRectangleIcon as LogOutIcon,
  MagnifyingGlassIcon as SearchIcon,
  PlusIcon as AddIcon,
  CalendarIcon,
  ChevronRightIcon as LastIcon,
  ChevronLeftIcon as FirstIcon,
  ArrowSmallRightIcon as NextIcon,
  ArrowSmallLeftIcon as PreviousIcon,
  ArrowUturnLeftIcon as BackIcon,
  ChevronUpDownIcon as ExpandIcon,
  CheckIcon,
};
