import { type HTMLAttributes } from "react";
import {
  DocumentPlusIcon,
  ArchiveBoxIcon,
  ArrowDownOnSquareIcon,
  ArrowRightOnRectangleIcon,
  ArrowSmallLeftIcon,
  ArrowSmallRightIcon,
  ArrowUpOnSquareIcon,
  ArrowUturnLeftIcon,
  ArrowsPointingOutIcon,
  Bars2Icon,
  BellAlertIcon,
  CalendarDaysIcon,
  CalendarIcon,
  ChatBubbleLeftRightIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpDownIcon,
  ClipboardDocumentCheckIcon,
  ClockIcon,
  Cog8ToothIcon,
  DocumentDuplicateIcon,
  DocumentMagnifyingGlassIcon,
  EllipsisHorizontalIcon,
  ExclamationTriangleIcon,
  EyeIcon,
  FlagIcon,
  FolderPlusIcon,
  FunnelIcon,
  GlobeAmericasIcon,
  GlobeEuropeAfricaIcon,
  HomeIcon,
  InboxIcon,
  MagnifyingGlassIcon,
  MapPinIcon,
  PencilIcon,
  PencilSquareIcon,
  PlusIcon,
  RectangleStackIcon,
  ShieldCheckIcon,
  SignalIcon,
  Square2StackIcon,
  SwatchIcon,
  TagIcon,
  TrashIcon,
  WrenchIcon,
  XMarkIcon,
} from "@heroicons/react/24/outline";

function WhombatIcon(props: HTMLAttributes<HTMLImageElement>) {
  return <img {...props} src="/whombat.svg" />;
}

export {
  ArchiveBoxIcon as DatasetIcon,
  ArrowDownOnSquareIcon as DownloadIcon,
  ArrowRightOnRectangleIcon as LogOutIcon,
  ArrowSmallLeftIcon as PreviousIcon,
  ArrowSmallRightIcon as NextIcon,
  ArrowUpOnSquareIcon as UploadIcon,
  ArrowUturnLeftIcon as BackIcon,
  ArrowsPointingOutIcon as TimeExpansionIcon,
  Bars2Icon as ChannelsIcon,
  BellAlertIcon as IssuesIcon,
  CalendarDaysIcon as DateIcon,
  CalendarIcon,
  ChatBubbleLeftRightIcon as NotesIcon,
  CheckCircleIcon as CompleteIcon,
  CheckIcon,
  ChevronLeftIcon as FirstIcon,
  ChevronRightIcon as LastIcon,
  ChevronUpDownIcon as ExpandIcon,
  ClipboardDocumentCheckIcon as EvaluationIcon,
  ClockIcon as TimeIcon,
  Cog8ToothIcon as SettingsIcon,
  DocumentDuplicateIcon as RecordingsIcon,
  DocumentMagnifyingGlassIcon as ExplorationIcon,
  EllipsisHorizontalIcon as SampleRateIcon,
  ExclamationTriangleIcon as WarningIcon,
  EyeIcon as NeedsReviewIcon,
  FlagIcon as IssueIcon,
  FolderPlusIcon as AddRecordingIcon,
  FunnelIcon as FilterIcon,
  GlobeAmericasIcon as LongitudeIcon,
  GlobeEuropeAfricaIcon as LatitudeIcon,
  HomeIcon,
  InboxIcon as MessagesIcon,
  MagnifyingGlassIcon as SearchIcon,
  MapPinIcon as LocationIcon,
  PencilIcon as EditIcon,
  PencilSquareIcon as AnnotationProjectIcon,
  PlusIcon as AddIcon,
  RectangleStackIcon as DatasetsIcon,
  RectangleStackIcon as TasksIcon,
  ShieldCheckIcon as VerifiedIcon,
  SignalIcon as SoundEventIcon,
  Square2StackIcon as ClipsIcon,
  SwatchIcon as TagsIcon,
  TagIcon,
  TrashIcon as DeleteIcon,
  WhombatIcon,
  WrenchIcon as MissingIcon,
  XMarkIcon as CloseIcon,
  DocumentPlusIcon as NewRecordingIcon,
};
