import { type ComponentProps } from "react";
import Image from "next/image";
import {
  AdjustmentsVerticalIcon,
  ArchiveBoxIcon,
  ArrowDownOnSquareIcon,
  ArrowLeftOnRectangleIcon,
  ArrowPathRoundedSquareIcon,
  ArrowRightOnRectangleIcon,
  ArrowSmallLeftIcon,
  ArrowSmallRightIcon,
  ArrowUpOnSquareIcon,
  ArrowUturnLeftIcon,
  ArrowsPointingOutIcon,
  Bars2Icon,
  BellAlertIcon,
  BoltIcon,
  CalendarDaysIcon,
  CalendarIcon,
  ChartBarSquareIcon,
  ChatBubbleBottomCenterTextIcon,
  ChatBubbleLeftRightIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpDownIcon,
  ClipboardDocumentCheckIcon,
  ClipboardDocumentListIcon,
  ClockIcon,
  Cog8ToothIcon,
  CursorArrowRaysIcon,
  DocumentDuplicateIcon,
  DocumentIcon,
  DocumentMagnifyingGlassIcon,
  DocumentPlusIcon,
  EllipsisHorizontalIcon,
  ExclamationTriangleIcon,
  EyeIcon,
  FaceFrownIcon,
  FlagIcon,
  FolderPlusIcon,
  FunnelIcon,
  GlobeAmericasIcon,
  GlobeAsiaAustraliaIcon,
  GlobeEuropeAfricaIcon,
  HandRaisedIcon,
  HomeIcon,
  InboxIcon,
  LinkIcon,
  MagnifyingGlassIcon,
  MagnifyingGlassPlusIcon,
  MapPinIcon,
  PauseIcon,
  PencilIcon,
  PencilSquareIcon,
  PlayIcon,
  PlusIcon,
  RectangleStackIcon,
  ShieldCheckIcon,
  SignalIcon,
  SpeakerWaveIcon,
  Square2StackIcon,
  SquaresPlusIcon,
  SwatchIcon,
  TagIcon,
  TrashIcon,
  WrenchIcon,
  XMarkIcon,
} from "@heroicons/react/24/outline";

function WhombatIcon(props: Omit<ComponentProps<typeof Image>, "src" | "alt">) {
  return <Image alt="Whombat Logo" src="/whombat.svg" {...props} />;
}

export {
  ArchiveBoxIcon as DatasetIcon,
  ArrowDownOnSquareIcon as DownloadIcon,
  ArrowRightOnRectangleIcon as LogOutIcon,
  ArrowSmallLeftIcon as PreviousIcon,
  ArrowSmallRightIcon as NextIcon,
  ArrowUpOnSquareIcon as UploadIcon,
  ArrowUturnLeftIcon as BackIcon,
  ArrowsPointingOutIcon as TimeExpansionIcon,
  Bars2Icon as ChannelsIcon,
  BellAlertIcon as IssuesIcon,
  CalendarDaysIcon as DateIcon,
  CalendarIcon,
  ChatBubbleLeftRightIcon as NotesIcon,
  CheckCircleIcon as CompleteIcon,
  CheckIcon,
  ChevronLeftIcon as FirstIcon,
  ChevronRightIcon as LastIcon,
  ChevronUpDownIcon as ExpandIcon,
  ClipboardDocumentCheckIcon as EvaluationIcon,
  ClockIcon as TimeIcon,
  Cog8ToothIcon as SettingsIcon,
  DocumentDuplicateIcon as RecordingsIcon,
  DocumentMagnifyingGlassIcon as ExplorationIcon,
  EllipsisHorizontalIcon as SampleRateIcon,
  ExclamationTriangleIcon as WarningIcon,
  EyeIcon as NeedsReviewIcon,
  FlagIcon as IssueIcon,
  FolderPlusIcon as AddRecordingIcon,
  FunnelIcon as FilterIcon,
  GlobeAmericasIcon as LongitudeIcon,
  GlobeEuropeAfricaIcon as LatitudeIcon,
  HomeIcon,
  InboxIcon as MessagesIcon,
  MagnifyingGlassIcon as SearchIcon,
  MapPinIcon as LocationIcon,
  PencilIcon as EditIcon,
  PencilSquareIcon as AnnotationProjectIcon,
  PlusIcon as AddIcon,
  RectangleStackIcon as DatasetsIcon,
  RectangleStackIcon as MissingTaskIcon,
  ShieldCheckIcon as VerifiedIcon,
  SignalIcon as SoundEventIcon,
  Square2StackIcon as ClipsIcon,
  SwatchIcon as TagsIcon,
  TagIcon,
  TrashIcon as DeleteIcon,
  WhombatIcon,
  WrenchIcon as MissingIcon,
  XMarkIcon as CloseIcon,
  DocumentPlusIcon as NewRecordingIcon,
  DocumentIcon as RecordingIcon,
  GlobeAsiaAustraliaIcon as MapIcon,
  AdjustmentsVerticalIcon as SpectrogramSettingsIcon,
  SpeakerWaveIcon as AudioIcon,
  ChartBarSquareIcon as SpectrogramIcon,
  ChatBubbleBottomCenterTextIcon as NoteIcon,
  ArrowLeftOnRectangleIcon as GoToIcon,
  LinkIcon,
  PlayIcon,
  PauseIcon,
  SpeakerWaveIcon as VolumeIcon,
  BoltIcon as SpeedIcon,
  ArrowPathRoundedSquareIcon as LoopIcon,
  HandRaisedIcon as DragIcon,
  MagnifyingGlassPlusIcon as ZoomIcon,
  FaceFrownIcon as SadIcon,
  ClipboardDocumentListIcon as TasksIcon,
  SquaresPlusIcon as NewAnnotationIcon,
  CursorArrowRaysIcon as SelectIcon,
};
