"""Removed unnecessary id from clip prediction tag.

Revision ID: b9f0f5a64c37
Revises: ef4af2e772f7
Create Date: 2024-09-24 16:36:17.757109

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9f0f5a64c37"
down_revision: Union[str, None] = "ef4af2e772f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("clip_prediction_tag") as batch_op:
        batch_op.drop_column("id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("clip_prediction_tag") as batch_op:
        batch_op.add_column(sa.Column("id", sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
