name: Build Frontend

on:
  workflow_call:

jobs:
  build-frontend:
    name: Build Frontend

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"
          cache-dependency-path: |
            front/package-lock.json

      - name: Install frontend dependencies
        run: |
          cd front
          npm ci

      - name: Build frontend app
        run: |
          cd front
          npm run build

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: front/out
