name: Build Frontend

on:
  workflow_call:

jobs:
  build-user-guide:
    name: Build User Guide

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.13
          working-directory: back

      - name: Install the project dependencies
        run: |
          cd back
          uv sync --all-extras --dev --locked

      - name: Build Guide
        run: |
          cd back
          uv run mkdocs build -d mkdocs-guide.yml -d site

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: user_guide
          path: back/site
