name: Make docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13
          enable-cache: true
          cache-dependency-glob: "back/uv.lock"
          pyproject-file: "back/pyproject.toml"

      - name: Restore mkdocs cache
        uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install the project dependencies
        run: |
          cd back
          uv sync --all-extras --dev --locked

      - name: Build and Deploy Docs
        run: |
          cd back
          uv run mkdocs gh-deploy --force
