name: Linting
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v3
      - name: Install dependencies
        run: |
          cd back
          rye sync
      - name: Check formatting and typing
        run: |
          cd back
          make lint
